#include QMK_KEYBOARD_H
//#include "dynamic_macro.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum stautonico_keycodes { QMKBEST = SAFE_RANGE , TO_FUNC};

enum layers {_QWERTY, _FUNC, _FN};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[_QWERTY] = LAYOUT(KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS,
        LCTL_T(KC_CAPS), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, RSFT_T(KC_SLSH), KC_UP, KC_DEL,
        KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_RALT, MO(_FUNC), KC_LEFT, KC_DOWN, KC_RGHT),
//                 KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_RALT, TO_FUNC, KC_LEFT, KC_DOWN, KC_RGHT),

[_FUNC] = LAYOUT(TG(_FN), KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS,
        KC_TRNS, RGB_TOG, RGB_M_P, RGB_M_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, RGB_HUI, RGB_SAI, RGB_VAI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDOWN, KC_END),

[_FN] = LAYOUT(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS,
        KC_TRNS, KC_7, KC_8, KC_9, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_4, KC_5, KC_6, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_1, KC_2, KC_3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
};


//bool process_record_user(uint16_t keycode, keyrecord_t *record) {
//    switch (keycode) {
//        case TO_FUNC:
//            if (record->event.pressed) {
//                rgblight_sethsv(0, 255, 255);
//                rgblight_mode(1);
////                rgblight_sethsv_at(39, 255, 255, 0);
////                rgblight_sethsv_at(39, 255, 255, 1);
//            } else {
//                rgblight_sethsv(262, 255, 255);
//                rgblight_mode(1);
////                rgblight_sethsv_at(39, 255, 255, 0);
////                rgblight_sethsv_at(39, 255, 255, 1);
//            }
//            return false;
//    }
//    return true;
//}

//bool process_record_user(uint16_t keycode, keyrecord_t *record) {
//    switch (keycode) {
//        case REPEATER:
//            if (record->event.pressed) {
//                //                SEND_STRING(SS_DOWN(X_LGUI) SS_TAP(X_F) SS_UP(X_LGUI) SS_DELAY(1000) SS_DOWN(X_LCTRL) SS_TAP(X_T) SS_DELAY(200) SS_TAP(X_A) SS_UP(X_LCTRL) SS_TAP(X_BSPACE) "https://twitch.tv/" SS_TAP(X_ENTER));
////                SEND_STRING(SS_DOWN(X_LGUI) SS_TAP(X_SPACE) SS_UP(X_LGUI) SS_DELAY(150) "firefox-developer-edition https://twitch.tv/" SS_TAP(X_ENTER));
//                spam_enter ^= 1;
//                spam_timer = timer_read();
//            }
//            return false;
//    }
//    return true;
//};
// changes underglow based on current layer
//#define RBG_VAL 120
//layer_state_t layer_state_set_user(layer_state_t state) {
//    switch(biton32(state)) {
//        case _QWERTY:
//            // green-ish
//            rgblight_sethsv_noeeprom(72, 221, RBG_VAL);
//            break;
//        case _FUNC:
//            // Red
//            rgblight_sethsv_noeeprom(0, 255, RBG_VAL);
//            break;
//        case _FN:
//            // Dark Blue
//            rgblight_sethsv_noeeprom(255, 0, RBG_VAL);
//            break;
//        default:
//            // Default colors
//            rgblight_sethsv(32, 170, RBG_VAL);
//            break;
//    }
//    return state;
//}